rds_admin_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;all
          30383165353964666234363861623736333762643130633934366361623739393636343933303962
          3836366465326162356263306265393030373764333561310a383766633832336634663537383932
          31316635366264623564383635313830643534653963363737396232356332323434326631346566
          3164663763363639350a323138383038383933653336353461366532623066343964666536333464
          61326363303662316234306133626365366564373031323239623762373633353862
# This is an access key belonging to the IAM user oaf-backups
backup_target_user: AKIAJBCNWWPWJUFEL7ZQ
backup_target_pass: !vault |
          $ANSIBLE_VAULT;1.2;AES256;all
          35626532383437323838646332376463323731666539623062313330623836626231333034623332
          6235633530393836383836623435303736333333666634330a656462333766653536356362336430
          33313930303264343835613437626430366434643033313836363930363439303866383036653437
          3339383334326133300a376235626262343236383936616164646665363965373633633330656636
          66333264353765356232383765393834373736633533613238313335636335376638363131663538
          6339643433633432366238306663396437343936383330306231
# Keep all backups around for six months by default
backup_max_age: 6M
backup_max_full_backups: 6
backup_full_max_age: 1M
certbot_webserver: apache

# Part of the default value "--quiet" appears not to be valid
certbot_auto_renew_options: "--no-self-upgrade"
github_users: ['mlandauer', 'henare', 'jamezpolley']
