---
theyvoteforyou_domain: theyvoteforyou.org.au
openaustralia_domain: openaustralia.org.au
righttoknow_domain: righttoknow.org.au
oaf_domain: oaf.org.au
opengovernment_domain: opengovernment.org.au
electionleaflets_domain: electionleaflets.org.au
ansible_user: ubuntu
ansible_ssh_private_key_file: 'test.pem'
ec2_region: 'ap-southeast-2'
# TODO: We only need this key to have limited privileges. It currently has too many privileges.
aws_access_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ec2
          33653434346236326464303936616138353065333937396366633539326164396566396334343462
          3034316131326463373931623639666265633062666636350a366539373361333738393530663161
          30333735303564316137363932333537626437646266633637633932376538656231366338366239
          3536386436363735630a333430386334646433646331393135646530396565613432393661653861
          36353437333761343736316161616164656437383961613365396462343438636339
aws_secret_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ec2
          37323435313134353264386530656139386132333938613063393334613738326339373437643166
          6332303235366437626564353231353932343062613562650a346539343161643764326163376439
          36616666666265316163653732303430363462613836353735656465656262383038633461653364
          6434643564643137640a333265323036303130353761613465313937653564303237306166643862
          63663031653636636137303266646532616635323635326365663134653539646639636465613766
          3334393761626366336464363162376430613638616235343437
mysql_host: "{{ rds_mysql.instance.endpoint }}"
postgresql_host: "{{ rds_postgresql.instance.endpoint }}"
planningalerts_db_host: "{{ rds_planningalerts.instance.endpoint }}"
newrelic_license_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;ec2
          63343465396536616465383664646636633632616133343734666464303438613965313037633032
          3666303962613737393233373835353663656464376564360a353936373031333930643833373163
          61373838343131393531393061646434613365336463333537306462313639373238656438336335
          6265303862363133330a343630383831303035613031303862633361366337636235366165386130
          61623365636130633264363330663661616635346432656164373937636631373633633238386633
          3664373363626161383364333230303662373865643130356366
devsite: false
