# TODO: Unify this with the domain. It's currently only used to name
# things on New Relic.
site_name: oaf.org.au
cron_enabled: true
admin_user: admin
admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33303833636365336362363632393135643063383339313938333639373439633039373966323962
          6262376236636437303639663838343033333833626437610a343261636234396436663564346136
          66366561343939326464313766343936623138386630333332613033326231343431306636323131
          3961343936386332310a616133346338313337333539666335343634383939313135363135333638
          36313561306433353764626263323937346363316365366232326234386137333461
oaf_production_mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35396633313434303266343366346161313665306639363763646337656138343165333566386434
          3039636331633631343963616463386432353738326165310a346563346130383039623461333435
          31646264643334653738393533393261333766336465366537626635323833663836653837353731
          6563303765396337380a326336333063346237306333653533346239333561613361623364653362
          65646531373862376562306131346139323439386335623531643361303838333537
civicrm_production_mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62363466633762356562363461386265313766653837323962343637356536386331663330613830
          3961663234353133393833353962326461333261646565360a663235393363323363633565333961
          35376134313564656136633731303135633833366138643137343131656437326463656438313633
          3735643262636639310a643465653166353261303838383539316236383338343431363932363963
          65383933663036343562376533623466373334366537613637623661316534626434
civicrm_wordpress_username: civicrm
civicrm_wordpress_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64666331613830393632336265366538363062656234336239346231656239303861663433393265
          3039313932353538646336623532303938343233303132650a396638313538643037633038326331
          64363966393830656132353163363636376361643333323564373439636466313130313363346637
          3736373036326533370a663039626465656533613162633637356335666366313635663761333933
          36363337663335323437633239313466633966316637373737343630303465343033
backup_gpg_pw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32336332646661613831376132353666323534303364303366306535646562653461653539613465
          3362316636313434326132646664633030623364616134630a633736313631616366386437333431
          39343833643364613532636139366361336234653535383830613332616639346131376434326466
          6265376239333462310a636430656236653031393138396636363730386263643164633738613439
          30663165306633383064643638313238303561616530626263643766396433303966
cuttlefish_smtp_pw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34383162663635393234343239356431646237663738633239656164326130373133303932323035
          3733313363633234616432363931316535393135343633350a613939613637653330333638326138
          63333239613833393930303936616639643066626136656433303365383130636534333762643561
          3434613564666235630a663730363562613937313465613463346633653966396539373136613630
          61633237353834316333623762386330663766396631636534633461666337333136
logs:
  - file_path: /var/log/syslog
    log_group_name: /var/log/syslog
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%b %d %H:%M:%S"

  - file_path: /var/log/apache2/error.log
    log_group_name: /var/log/apache2/error.log
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%a %b %d %H:%M:%S.%f %Y"

  - file_path: /var/log/duply/wordpress-uploads.log
    log_group_name: /var/log/duply/wordpress-uploads.log
    log_stream_name: "{{ inventory_hostname }}"
    # No idea what the format should be otherwise
    timestamp_format: "%b %d %H:%M:%S"

  - file_path: /var/log/letsencrypt/letsencrypt.log
    log_group_name: /var/log/letsencrypt/letsencrypt.log
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%Y-%m-%d %H:%M:%S"

  - file_path: /var/log/unattended-upgrades/unattended-upgrades.log
    log_group_name: /var/log/unattended-upgrades/unattended-upgrades.log
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%Y-%m-%d %H:%M:%S"
