# TODO: Unify this with the domain. It's currently only used to name
# things on New Relic.
name: planningalerts.org.au
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31623763313262306264356463636632336434613130656566353030396138326431613231616232
          3337643539666264643465306233613630633133333535630a623333343562366664666537366532
          62376262393932326538346265383632363763316362333339333362356565353161343833343361
          6139316663366630620a323835633334353632353132376464393835323165373066353366646330
          32363766633530653163366431613030393337373330386132663064666533373036
postgres_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66666333636464393733636564633435326363653237396561383163336435383730386137346138
          3763373532333534396666396236616264613739373336640a653837636433666637383465336135
          39356462386439366637356563643161393438346231623034386435613663333434633336623838
          3332613830383431360a326330353664323533326364653433613033653062313937646130373838
          63393332363765323630653635666536383861383232366263393162623532353835
mysql_password_readonly: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65376135383432366633376137353038326337353434613238616237316632616365376161326333
          6137386232636363343937323437376639666530336661640a353963623066396532636666646439
          64376664653239633062323764626535646438353535343633383630316162316632373139633964
          3234356635373464370a613331646166326233323830653162613063393834303264316136326265
          61343632373339363030666536666136346438633338353065333764636361306230
postgres_password_readonly: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36326533333762353938616163633439353765643830313066636333663339316361633266333064
          6338666565326537316431323736393030616133323636350a303635373637383138643631616338
          61613439626335356532636366613533323061393664616434636265363732343138646635306137
          6133383533373630370a323035646135393963613866373066333338366362663663396165366464
          34653933323338343734376533396563633762393965366362376165353130393961
cron_enabled: true
rails_master_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32393866613733333937346333353731396330326531363837396632633761343731633436636330
          6137343761653132653632373430613963653935306331660a326630653537336138313438393761
          38363464353361623461343735613736366435663165353231343931663962313434313364363365
          3065366466316630370a306262373564666438623035363033346561366136373464363933393561
          35336237313231363663626261646263336462303135353433303363386261323335306561616663
          3030353663346162343339626262653662333234333162623163
ingress_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39346339376433313532636565363138643832373630656366326431346236313662373864353766
          3564376333393666393038663335623863353439353836640a646536336361363362656130323862
          36653537623066356337383536376637613461363162306532393131623666393339333937626665
          3931653038653361300a386238613534623765373031636330376562356238663432633865396536
          61323234666339626664363939633161333936653231646466633666343062323636
logs:
  - file_path: /var/log/syslog
    log_group_name: /var/log/syslog
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%b %d %H:%M:%S"

  - file_path: /var/log/unattended-upgrades/unattended-upgrades.log
    log_group_name: /var/log/unattended-upgrades/unattended-upgrades.log
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%Y-%m-%d %H:%M:%S"

  - file_path: /srv/www/production/shared/log/production.log
    log_group_name: /srv/www/production/shared/log/production.log
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%Y-%m-%dT%H:%M:%S.%f"
