site_name: plausible.oaf.org.au
secret_key_base: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63663637316331323333393266623234343565316435376539353031383035343737393738633137
          6633383431343238343239616533626566623166393135640a633039393161376262653463613039
          37613037613832616332366631366139343864616633663965326338636632356365373561306132
          6665616132353830640a343265666564343630356130373334336138343164316233326337316162
          35643638613865313633306565366263313564343038313163333836376338666165323331613531
          38393233666135636536333136343937373364303133343064636131313635626134376562636132
          32373037646362363533613332346537356263316666623034356563663061363264313466623563
          37666535653732303433
db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35383334653865366530336132333032626237333265653631326231333434666331313365663436
          3961663437616331373037356138346335613830356637630a383031303936326661653739316132
          33323431343634623238383236643530616237376663366233303133343966616135343364303065
          6432623734633462370a373939646430396366626639306233393866383065313035373331363834
          63383838303936363735643432386134633239363039636234363737366632393539