# Right to Know Standalone Production Server
# Most values are inherited from the existing righttoknow.yml

# TODO: Unify this with the domain. It's currently only used to name
# things on New Relic.
name: prod.righttoknow.org.au

# Domain configuration for standalone production server
righttoknow_domain: righttoknow.org.au # Used in certbot and SSL
domain: righttoknow.org.au # Used in Nginx
server_hostname: prod.righttoknow.org.au # Used in Nginx and certbot