# TODO: Unify this with the domain. It's currently only used to name
# things on New Relic.
name: theyvoteforyou.org.au
# Not using any non-alphanumeric characters in the password so that we can use
# ansible-vault encrypt_string without having to use stdin input (which appears to
# introduce an extra carriage return at the end)
certbot_webserver: nginx
theyvoteforyou_production_mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34656533336664366134363064326334616662353834333530386238323062643366653166666237
          3536346538326162656265353661663462363366383332300a633464666162353963393536633864
          35323665343231633065323237393838303533303363666234323163646237306364343662666161
          6536373035616233660a313466656532336231626162623435316634346334386339343032623131
          64646530646132383031376231396663303139366239663666636531363732323932
theyvoteforyou_staging_mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31616266616536306631643361623234383739623833656563343335626331363539643064616437
          3532346534313132616661356666653039353236323336340a333039663761623666316463343336
          64363764636430626362356330613835383639633336646262613462386230643962343637386531
          3266323763333366350a363262336430323738653131623237643138663436363132353664386263
          63373333373733303962396235633666396563313234333063633634366635323862
mysql_production_password_readonly: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30366530663866396635383730323463396334366635623931646536366664306363653862333834
          6334633965376338313161343632356637346135353163380a363934313366383938613264643862
          65646231363538363930623535323963623838663365383465633631636361653435326165353563
          3833353337613239370a393331333332633763313439623064346639373635666230303937303235
          63663633613265643862613664633834656230333933343433386338623765623539
# Until this is being used properly in production disable the cron
cron_enabled: true
secret_key_base: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38346265626364643637323161346332313165386466336639343161646164653061373165313530
          6532316132643239333934336163393736666333396636610a393762343766386161396463393239
          34646261363663623864623335383834353831613831306363663961643636363831383537366338
          6637663663623663310a393432366434326131393835386364653437616537303737616364393132
          66626366393330376233373135653338393466613063653635383461363037316665353032613464
          37643832353864616533306333613932396631316364643862346138343435636237373633613434
          33643532383931616663353863656632643163393131326361623834646535333336656233613362
          37336166306431363731613930643432656163636564383533616238366132316462356162623332
          37633238383039336134313239613662663139353861366261643035653565316263636639376364
          65643364346235333738666137333836333066646536323830323266363438646431383530303831
          306663326263653437323331613637663235
cuttlefish_server: cuttlefish.oaf.org.au
cuttlefish_user_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31656663616335333364396538623766663036373763373534313931373563316561383264633231
          3862663266643632383537643833393632363937323263640a383833653239663735333063633461
          38373633366631636366393537623638623065626235623535393665303562646561363538303562
          3637623532663531370a366461336436353837383537613062613438363132643636353033313564
          37386362313330656638613233353563313066613137333739356135623330643365
cuttlefish_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66623834666365346164316266626163316233393838616366323339663930633839303862653565
          3861316562323931393262653436363263313637636133610a663330386639653566316365333135
          30626238323064396233656561353830643165356464396437386638663133323337396238653339
          6565306435623161620a656330653732353535323139616131353039386430613035623063323262
          33323634376263613461363532393035613939333334323233346431363530613661
honeybadger_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64643934643838346633326264373339613330616330336565303064636336376464316262356131
          3534653533616230343965393535643436396663333938650a333334663232353539633739356561
          31366334386236643161653330313538343930663465373131346239616564383238613261336530
          6464353335363837320a653038393432393536663530356139646365356265616562323635656534
          6431
honeybadger_javascript_api_key: hbp_WK1QYFt2gDHC2X48Ln8RY2VkNNCz6p15QAob
elasticsearch_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66323061396662656534393931383231303130323435326463656332346438663363356465363531
          6461386338306431623833626563323835303966333434320a386666396366313561616364633237
          64303132353264626330336538336537623834393233323134663733393864313565333032616236
          6264323763363366320a613830396262643133613163353739316336383438333166383739316535
          36393137666461636266323061396137623762303430663365363532396436313133333163336634
          33633261616261313139363538623736303836396265353830623732346164623739393539303534
          34313433396364303533393430643636386435323738366235626336306433353936393661643666
          64326631343839393761373635346561303233353361333165643532353730643466303530653066
          32313733363338373239623731336664393736373665346135373634336264303635
urlbox_apikey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62373464346430346134653530306161343632373265356531633237353665303465316432666338
          3632373735393735316537666131343562373261396433620a316264643533616338306237343934
          33323530323661303035656665363334303239346233653865623434343634303364633964323662
          6133663436353132310a396138366236613935316263656139363231653138346662343730383234
          66383161303235363733333766333065303364323233353335316165663435653836
urlbox_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62366338336335656330306130643333646230623238363065623034326634316230633630613465
          3164323464643066383131333338336133323034313766640a653337346361613230356536633861
          35373561636265356134666462663438363062313238366339613063333735653464643864636633
          3237653230306463300a316439386265633263303263383833393462313130373539313733343835
          36613264636138313534653335313562343535336139343631393530656238363134373133613762
          6564303065653764643166326265313064653238306665303564
google_analytics_code: UA-3107958-15
skylight_authentication: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61623935353735333363316638306661333038396431396364333738653533326138303033323032
          3261633464363738633363383532303036653731366139370a383063393861643632383763633232
          36343836353038363764336433366338333732623265613762363836643734633339653630303262
          3130666566613032310a356535383164393933393933373663313564646265363232666265313932
          64343364316365373166316264393366623663366230376238303334663262306635346361383364
          3761363462626265303139666637646465386234303464666438
logs:
  - file_path: /var/log/syslog
    log_group_name: /var/log/syslog
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%b %d %H:%M:%S"

  - file_path: /var/log/nginx/error.log
    log_group_name: /var/log/nginx/error.log
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%Y-%m-%d %H:%M:%S.%f"

  - file_path: /var/log/letsencrypt/letsencrypt.log
    log_group_name: /var/log/letsencrypt/letsencrypt.log
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%Y-%m-%d %H:%M:%S"

  - file_path: /var/log/unattended-upgrades/unattended-upgrades.log
    log_group_name: /var/log/unattended-upgrades/unattended-upgrades.log
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%Y-%m-%d %H:%M:%S"

  - file_path: /srv/www/production/shared/log/production.log
    log_group_name: /srv/www/production/shared/log/production.log
    log_stream_name: "{{ inventory_hostname }}"
    timestamp_format: "%Y-%m-%dT%H:%M:%S.%f"
