---
- include_vars: encrypted.yml
- include_vars: encrypted_vars/dnsmadeeasy.yml

- name: Ensure that deploy owns /srv/www and /srv/www/shared
  file:
    state: directory
    owner: deploy
    group: deploy
    path: "{{item}}"
  with_items:
    - /srv/www
    - /srv/www/shared

# Installing via bash so that rbenv is used. Otherwise would install gems for default system ruby
# TODO When gem is already installed stop it from saying something has changed
- name: Install bundler gem
  command: bash -lc "gem install bundler"
  sudo: true
  sudo_user: deploy

- name: Install packages required by Alaveteli
  apt: name={{ item }} state=present
  with_items:
    - libicu-dev
    - libmagic-dev
    - libmagickwand-dev
    - xapian-tools
    - uuid-dev

- name: Create database
  postgresql_db: name=alaveteli

- name: Create posgresql role
  postgresql_user: db=alaveteli name=alaveteli password={{ db_password }}

- name: Copy over database configuration for application
  template: src=database.yml dest=/srv/www/shared/database.yml owner=deploy group=deploy
  notify: nginx restart

- name: Copy init scripts for daemons
  copy:
    dest: /etc/init.d/
    src: "{{ item }}"
    mode: 0755
  with_items:
    - foi-alert-tracks
    - foi-purge-varnish

- name: Generate the overall nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: nginx reload

- name: Generate the nginx config for the app
  template: src=default dest=/etc/nginx/sites-available/ owner=root group=root mode=644
  notify: nginx reload

- name: Copy across the main Alaveteli config
  template: src=general.yml dest=/srv/www/shared/ owner=deploy group=deploy
  notify: nginx restart

- name: Add SSL certificate
  copy: src=ssl-unified.crt dest=/etc/ssl/righttoknow.org.au.dev.pem owner=root group=root mode=0644
  notify: nginx reload

- name: Add private SSL key
  copy: content="{{ private_ssl_key }}" dest=/etc/ssl/private/righttoknow.org.au.dev.key owner=root group=ssl-cert mode=0640
  notify: nginx reload

- name: Add alaveteli crontab entry
  cron: name="foi-alert-tracks" minute="0,10,20,30,40,50" job="/bin/bash -l -c 'sudo /etc/init.d/foi-alert-tracks check'"

- name: Add alaveteli crontab entry
  cron: name="foi-purge-varnish" minute="0,10,20,30,40,50" job="/bin/bash -l -c 'sudo /etc/init.d/foi-purge-varnish check'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="holidays" minute="0" hour="0" day="1" month="12" job="/bin/bash -l -c '/bin/echo \"A year has passed, please update the bank holidays for the Freedom of Information site, thank you.\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="alert-comment-on-request" minute="9" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production run-with-lockfile -n ./alert-comment-on-request ./script/alert-comment-on-request || echo \"stalled?\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="load-mail-server-logs" minute="31" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production run-with-lockfile -n ./load-mail-server-logs ./script/load-mail-server-logs || echo \"stalled?\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="update-xapian-index" minute="0,5,10,15,20,25,30,35,40,45,50,55" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production run-with-lockfile -n ./update-xapian-index.lock \"./script/update-xapian-index verbose=true\" >> ./log/update-xapian-index.log || echo \"stalled?\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="delete-old-things" minute="23" hour="4" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production run-with-lockfile -n ./delete-old-things ./script/delete-old-things || echo \"stalled?\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="alert-overdue-requests" minute="0" hour="6" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production run-with-lockfile -n ./alert-overdue-requests ./script/alert-overdue-requests || echo \"stalled?\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="alert-new-response-reminders" minute="0" hour="7" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production run-with-lockfile -n ./alert-new-response-reminders ./script/alert-new-response-reminders || echo \"stalled?\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="alert-not-clarified-request" minute="0" hour="8" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production run-with-lockfile -n ./alert-not-clarified-request ./script/alert-not-clarified-request || echo \"stalled?\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="check-recent-requests-sent" minute="2" hour="4" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production run-with-lockfile -n ./check-recent-requests-sent ./script/check-recent-requests-sent || echo \"stalled?\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="stop-new-responses-on-old-requests" minute="45" hour="3" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production run-with-lockfile -n ./stop-new-responses-on-old-requests ./script/stop-new-responses-on-old-requests || echo \"stalled?\"'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="request-creation-graph" minute="43" hour="2" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production ./script/request-creation-graph'"

- name: Add alaveteli crontab entry
  cron: user=deploy name="user-use-graph" minute="48" hour="2" job="/bin/bash -l -c 'cd /srv/www/current && RAILS_ENV=production ./script/user-use-graph'"

- name: DNS setup for righttoknow.org.au
  dnsmadeeasy: account_key={{ dnsmadeeasy_key }} account_secret={{ dnsmadeeasy_secret }} domain="righttoknow.org.au" record_ttl=1800 state=present record_name="{{ item.name }}" record_type="{{ item.type }}" record_value='{{ item.value }}'
  tags:
    - dns
  with_items:
    - {type: "A", name: "", value: "103.243.244.10"}
    - {type: "CNAME", name: "www",  value: ""}
    - {type: "CNAME", name: "test", value: ""}
    - {type: "MX", name: "", value: "10 aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt1.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "20 alt2.aspmx.l.google.com."}
    - {type: "MX", name: "", value: "30 aspmx2.googlemail.com."}
    - {type: "MX", name: "", value: "30 aspmx3.googlemail.com."}
    - {type: "MX", name: "server", value: "10 "}
    - {type: "TXT", name: "", value: '"v=spf1 a include:_spf.google.com ~all"'}
    - {type: "TXT", name: "", value: "google-site-verification=CPi5guMn0IiJjjYusPOb3ziStX_vKDqyk-cs0cLZvHc"}
