# file: timezone/meta/main.yml

galaxy_info:
  author: pjan vandaele
  company: ANXS
  description: set/update the timezone
  min_ansible_version: 1.2
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system

dependencies: []
