name: terraform-init
on:
  pull_request:
    branches:
      - main
jobs:
  tf-init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: "ls -l"
        - run: ./.github/scripts/setup-terraform.sh
        - run: terraform -chdir=terraform init -input=false 
        - run: |
            if [[ -n "$(git status --porcelain)" ]]; then
                echo "Error: Uncommitted changes or untracked files detected."
                git status
                exit 1
            fi
